#!/bin/sh

compare() {
	n=$2
	n=$((n+1))

	# Get the temperature from the sample
	head -n1 "$test_data_file" | cut -f$n > propiedades
	# Get the sample data and send it to the comparison file
	awk -F'\t' -v n="$n" '{print $1","$n}' "$test_data_file" > "$compare_file"

	# Erase all the calculated data except the columns names
	head -n1 "$gerg_data_file" > /tmp/gergdata
	cat /tmp/gergdata > "$gerg_data_file"


	n=$((n+1))
	cat propiedades "$test_folder/concentrations" | 
		awk -v n="$n" '{print $1,$2,$n}' |
		./gerg isotherm | awk '{print $1","$2","$3","$4","$5}' >> "$gerg_data_file"
	echo "comp,conc" > "$test_folder/tmp_conc"
	cat "$test_folder/concentrations" |
		awk -v n="$n" '{print $2","$n}' >> "$test_folder/tmp_conc"

	# It's actually n samples + 1 since it counts the X column
	cd "$test_folder"
	python compare.py $((n-2)) "$1"
	cd ..
}

batch_run() {
	i=1
	while [ $i -lt $n_samples ];do
		compare $1 $i
		i=$((i+1))
	done
}



case $1 in
	"Z")
	col=4
	test_folder="Z_test"
	compare_file="$test_folder/compare"
	test_data_file="$test_folder/test_data"
	gerg_data_file="$test_folder/gergdata"

	n_samples=$(awk '{print NF}' "$test_data_file" | sort -nu | tail -n1)

	[ -z $2 ] && batch_run && exit 0
	compare $2;;

	"w")
	test_folder="w_test"
	compare_file="$test_folder/compare"
	test_data_file="$test_folder/test_data"
	gerg_data_file="$test_folder/gergdata"

	n_samples=$(awk '{print NF}' "$test_data_file" | sort -nu | tail -n1)

	[ -z $2 ] && batch_run "$1" && exit 0
	compare "$1" $2;;
esac

