#!/bin/sh

text=$(xclip -sel clip -o | 
	tr '−' ' -' |
	tr '·10' 'E' |
	sed 's/^ //;s/^[0-9] *$//' | 
	sed '/^$/d' |
	sed 's/^[A-Za-z]/\n/'
)

values="$(cut $1 -d' ' -f2- | tr '\n' ' ' | sed 's/0\.0 //g')"

echo "$text" > $2

for val in $values; do
	sed -i "s/$val//" $2
done


